[package]
name = "memory"
version = "0.1.0"
edition = "2021"

[dependencies]

uuid = { version = "1.4", features = ["v4", "serde"] }

axum = "0.7.5"
serde_json = "1.0"
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
http-body-util = "0.1.0"
mime = "0.3"
tower = { version = "0.4", features = ["util"] }
hyper-util = { version = "0.1", features = [
    "client",
    "http1",
    "client-legacy",
] }
