[package]
name = "in_memory_database"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/in_memory.rs"

[dependencies]
async-trait.workspace = true
database.workspace = true
domain.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
