[package]
name = "database"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/database.rs"

[dependencies]
async-trait.workspace = true
domain.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
