[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/domain.rs"

[dependencies]
chrono.workspace = true
ferrochain.workspace = true
serde.workspace = true
uuid.workspace = true
